### ISSUE TITLE
Planned refactors and changes

### ISSUE THREAD

**Issue by henryiii** [scientific-python/repo-review#50]
- [x] Fixtures need entry point. #52
- [x] Family as attribute (sorted). #55
- [x] Check/rating unify language. #57
- [x] `--url` (auto?) loading. #56

Design related:
- [x] Maybe some way to sort families. #62
- [x] Branching checks mechanism (backends, for example, maybe even special cased) #60
    - [x] See if instances work too #63

**Comment by henryiii** [comment]
Pretty much, this is basically the todo list of things that might change the API for plugins (well, except for URL, but that's easy). Getting these done before the split would be ideal.

**Comment by henryiii** [comment]
Refactored. Starting split next.

**Comment by henryiii** [comment]
Remaining things before a non-beta release (at beta 2 currently):

- [ ] Update readme
- [ ] Basic docs on writing checks / fixtures
- [ ] Some downstream checking to make sure sp-repo-review works

**Comment by henryiii** [comment]
This is pretty close to a non-beta release. @pllim or @Carreau, let me know if you have any final thoughts. Docs are up at https://repo-review.readthedocs.org, with details on how to write plugins with fixtures & checks.

**Comment by pllim** [comment]
Hello! At a glance, would be nice for the doc to have "Install" and "Getting Started". I would like to know how to install the engine and then build customized checks (the latter seems to be covered well in the docs).

Also, did you say you plan to have Action workflow as well at some point, or maybe I got confused with a different effort at the summit?

Thanks! 😸

**Comment by henryiii** [comment]
I do have an action (#45), but it's not really very useful without a plugin - there are no built-in checks. And you'd want to have the action pinned on the plugin, I'd expect, so it's more of an example for plugins than a useful thing by itself. Same thing is a bit of an issue for supporting pre-commit (#48), and a reason I didn't really have a installing/getting started - you can't do anything without installing at least one plugin. But (like the web app), I can do it with `sp-repo-review` as an example, I guess.

**Comment by henryiii** [comment]
Okay, finished off the action & pre-commit, plus added some docs.

**Comment by pllim** [comment]
Do you think the engine could come with one plugin shipped so it could run as-is? Is there some check that everybody wants? flake8? 🤔

**Comment by pllim** [comment]
Thank you, the updated doc is super helpful!

**Comment by henryiii** [comment]
Repo-review doesn't make any assumptions about what is in the repo you want to review. It doesn't have to be Python. It does provide a `pyproject` fixture, since it supports reading config from pyproject.toml, but one doesn't need to exist. It also does have integrated support for a "package" separate from the repo "root", but that's not Python specific.

I'm just using sp-repo-review as the demo, and maybe we could make a repo-review-example repo or something like that in the future with a few example checks.

Also, does anyone still use flake8 now that Ruff exists? Every repo I'm involved with transitioned to Ruff some time ago.

![star-history-202367](https://github.com/scientific-python/repo-review/assets/4616906/2613974e-1d8b-49dc-bf48-a990271d6d01)
